repos:
-   repo: https://github.com/ambv/black
    rev: 23.11.0
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace

- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.1.6'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

# manually run mypy check temporarily
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.991
#     hooks:
#     - id: mypy
#       exclude: ^tests/

-   repo: local
    hooks:
    -   id: export-requirements
        name: Convert pyproject.toml to requirements.txt
        language: system
        entry: poetry export --dev -f requirements.txt --without-hashes --output requirements.txt
        files: "^pyproject.toml$"
        pass_filenames: false
